FROM microsoft/dotnet:2.2-aspnetcore-runtime AS builder
WORKDIR /jobrangerapp

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish --output /app/ --configuration Release

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=builder /app.
CMD ["dotnet", "JobRanger.dll"]