FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS builder
WORKDIR /app

COPY *.csproj ./

RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /jobrangerapp
COPY --from=builder /app/out .



# CMD ["dotnet", "Program.cs"]

ENTRYPOINT ["dotnet","JobRanger.dll"]